ANDROID: Symbols missing from ksymtab
ERROR: Differences between ksymtab and symbol list detected!
Symbols missing from ksymtab:
 - log_abnormal_wakeup_reason
 - log_threaded_irq_wakeup_reason
 - pm_get_active_wakeup_sources

Signed-off-by: dopaemon <polarisdp@gmail.com>