display/msm/sde: Remove unused function
../../../../../../kernel/oneplus/sm8450-modules/qcom/opensource/display-drivers/msm/sde/sde_hw_interrupts.c:672:13: error: unused function sde_hw_intr_clear_intr_status_nolock [-Werror,-Wunused-function]
  672 | static void sde_hw_intr_clear_intr_status_nolock(struct sde_hw_intr *intr,
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

Change-Id: I62156c627a9044d8ac38199d198b10ec19ecbdcd
Signed-off-by: Weikai Kong <priv@pppig236.com>
Signed-off-by: dopaemon <polarisdp@gmail.com>